package Leffasovellus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Leffasovellus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.28 19:36:35 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class ElokuvaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi37 */
  @Test
  public void testRekisteroi37() {    // Elokuva: 37
    Elokuva elokuva = new Elokuva(); 
    assertEquals("From: Elokuva line: 39", 0, elokuva.getId()); 
    elokuva.rekisteroi(); 
    Elokuva elokuva2 = new Elokuva(); 
    elokuva2.rekisteroi(); 
    int n1 = elokuva.getId(); 
    int n2 = elokuva2.getId(); 
    assertEquals("From: Elokuva line: 45", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi91 */
  @Test
  public void testGetNimi91() {    // Elokuva: 91
    Elokuva elokuva = new Elokuva(); 
    elokuva.parse("4|Avatar|James Cameron|2009|fantasia|161 "); 
    assertEquals("From: Elokuva line: 94", "Avatar", elokuva.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse151 */
  @Test
  public void testParse151() {    // Elokuva: 151
    Elokuva elokuva = new Elokuva(); 
    elokuva.parse("4|Avatar|James Cameron|2009|fantasia|161 "); 
    assertEquals("From: Elokuva line: 154", "161", elokuva.getKesto()); 
    assertEquals("From: Elokuva line: 155", 4, elokuva.getId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString187 */
  @Test
  public void testToString187() {    // Elokuva: 187
    Elokuva elokuva = new Elokuva(); 
    elokuva.parse("4|Avatar|James Cameron|2009|fantasia|161"); 
    assertEquals("From: Elokuva line: 190", "4|Avatar|James Cameron|2009|fantasia|161|", elokuva.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone209 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone209() throws CloneNotSupportedException {    // Elokuva: 209
    Elokuva elokuva = new Elokuva(); 
    elokuva.parse("6|Titanic|James Cameron|1997|draama|127"); 
    Elokuva kopio = elokuva.clone(); 
    assertEquals("From: Elokuva line: 214", elokuva.toString(), kopio.toString()); 
    elokuva.parse("6|Titanic|James Cameron|1997|fantasia|127"); 
    assertEquals("From: Elokuva line: 216", false, kopio.toString().equals(elokuva.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna283 */
  @Test
  public void testAnna283() {    // Elokuva: 283
    Elokuva elo = new Elokuva(); 
    elo.parse("5|Avatar|James Cameron| fantasia| 2009|161"); 
    assertEquals("From: Elokuva line: 286", "5", elo.anna(0)); 
    assertEquals("From: Elokuva line: 287", "James Cameron", elo.anna(2)); 
    assertEquals("From: Elokuva line: 288", "161", elo.anna(5)); 
  } // Generated by ComTest END
}