package Leffasovellus.test;
// Generated by ComTest BEGIN
import Leffasovellus.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:36:11 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkilotTest {



  // Generated by ComTest BEGIN
  /** 
   * testHenkilotIterator196 
   * @throws SailoException when error
   */
  @Test
  public void testHenkilotIterator196() throws SailoException {    // Henkilot: 196
    Henkilot henkilot = new Henkilot(); 
    Henkilo henk = new Henkilo(), henk2 = new Henkilo(); 
    henk.rekisteroi(); henk2.rekisteroi(); 
    henkilot.lisaa(henk); 
    henkilot.lisaa(henk2); 
    henkilot.lisaa(henk); 
    StringBuffer ids = new StringBuffer(30); 
    for (Henkilo henkilo : henkilot)
    ids.append(" "+henkilo.getTunnusNro()); 
    String tulos = " " + henk.getTunnusNro() + " " + henk2.getTunnusNro() + " " + henk.getTunnusNro(); 
    assertEquals("From: Henkilot line: 215", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Henkilo>  i=henkilot.iterator(); i.hasNext(); ) {
    Henkilo henkilo = i.next(); 
    ids.append(" "+henkilo.getTunnusNro()); 
    }
    assertEquals("From: Henkilot line: 223", tulos, ids.toString()); 
    Iterator<Henkilo>  i=henkilot.iterator(); 
    assertEquals("From: Henkilot line: 226", true, i.next() == henk); 
    assertEquals("From: Henkilot line: 227", true, i.next() == henk2); 
    assertEquals("From: Henkilot line: 228", true, i.next() == henk); 
    try {
    i.next(); 
    fail("Henkilot: 230 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}