package Leffasovellus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Leffasovellus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:36:02 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi21 */
  @Test
  public void testRekisteroi21() {    // Henkilo: 21
    Henkilo henk = new Henkilo(); 
    assertEquals("From: Henkilo line: 23", 0, henk.getTunnusNro()); 
    henk.rekisteroi(); 
    Henkilo henk2 = new Henkilo(); 
    henk2.rekisteroi(); 
    int n1 = henk.getTunnusNro(); 
    int n2 = henk2.getTunnusNro(); 
    assertEquals("From: Henkilo line: 29", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi83 */
  @Test
  public void testGetNimi83() {    // Henkilo: 83
    Henkilo henk = new Henkilo(); 
    henk.parse("5|Pekka"); 
    assertEquals("From: Henkilo line: 86", "Pekka", henk.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone124 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone124() throws CloneNotSupportedException {    // Henkilo: 124
    Henkilo henk = new Henkilo(); 
    henk.parse("   3  |  Maria"); 
    Henkilo kopio = henk.clone(); 
    assertEquals("From: Henkilo line: 129", henk.toString(), kopio.toString()); 
    henk.parse("   4  |  Anniina"); 
    assertEquals("From: Henkilo line: 131", false, kopio.toString().equals(henk.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse160 */
  @Test
  public void testParse160() {    // Henkilo: 160
    Henkilo henk = new Henkilo(); 
    henk.parse("   1   | Anniina   "); 
    assertEquals("From: Henkilo line: 163", 1, henk.getTunnusNro()); 
    henk.rekisteroi(); 
    int n = henk.getTunnusNro(); 
    henk.parse(""+(n+4)); 
    henk.rekisteroi(); 
    assertEquals("From: Henkilo line: 169", n+4+1, henk.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString182 */
  @Test
  public void testToString182() {    // Henkilo: 182
    Henkilo henk = new Henkilo(); 
    henk.parse("2|Maria"); 
    assertEquals("From: Henkilo line: 185", "2|Maria|", henk.toString()); 
  } // Generated by ComTest END
}