package Leffasovellus.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Leffasovellus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.26 18:36:20 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KatsottuTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi22 */
  @Test
  public void testRekisteroi22() {    // Katsottu: 22
    Katsottu kat = new Katsottu(); 
    assertEquals("From: Katsottu line: 24", 0, kat.getTunnusNro()); 
    kat.rekisteroi(); 
    Katsottu kat2 = new Katsottu(); 
    kat2.rekisteroi(); 
    int n1 = kat.getTunnusNro(); 
    int n2 = kat2.getTunnusNro(); 
    assertEquals("From: Katsottu line: 30", (n2-1), n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetElokuvaId49 */
  @Test
  public void testGetElokuvaId49() {    // Katsottu: 49
    Katsottu kat = new Katsottu(); 
    kat.parse("1|3|4"); 
    assertEquals("From: Katsottu line: 52", 4, kat.getElokuvaId()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse110 */
  @Test
  public void testParse110() {    // Katsottu: 110
    Katsottu kat = new Katsottu(); 
    kat.parse(" 1 | 4 |6"); 
    assertEquals("From: Katsottu line: 113", 1, kat.getTunnusNro()); 
    kat.rekisteroi(); 
    int n = kat.getTunnusNro(); 
    kat.parse(""+(n+20)); 
    kat.rekisteroi(); 
    assertEquals("From: Katsottu line: 118", n+20+1, kat.getTunnusNro()); 
    assertEquals("From: Katsottu line: 119", "" + (n+20+1) + "|4|6|", kat.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString133 */
  @Test
  public void testToString133() {    // Katsottu: 133
    Katsottu kat = new Katsottu(); 
    kat.parse("   5 | 3   | 8"); 
    assertEquals("From: Katsottu line: 136", "5|3|8|", kat.toString()); 
  } // Generated by ComTest END
}