package Leffasovellus.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import Leffasovellus.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.28 19:36:47 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SovellusTest {



  // Generated by ComTest BEGIN
  /** testAnnaElokuvat204 */
  @Test
  public void testAnnaElokuvat204() {    // Sovellus: 204
    Sovellus sovellus = new Sovellus(); 
    Henkilo anniina = new Henkilo(), maria = new Henkilo(), jonne = new Henkilo(); 
    anniina.rekisteroi(); maria.rekisteroi(); jonne.rekisteroi(); sovellus.lisaa(anniina); sovellus.lisaa(maria); sovellus.lisaa(jonne); 
    int id1 = anniina.getTunnusNro(); 
    int id2 = maria.getTunnusNro(); 
    Elokuva titanic = new Elokuva(); titanic.rekisteroi(); sovellus.lisaa(titanic); 
    Elokuva grinch = new Elokuva(); grinch.rekisteroi(); sovellus.lisaa(grinch); 
    Katsottu katsottu = new Katsottu(); katsottu.rekisteroi(); sovellus.lisaa(katsottu); katsottu.setElokuvaId(1); katsottu.setHenkiloId(1); 
    Katsottu katsottu2 = new Katsottu(); katsottu2.rekisteroi(); sovellus.lisaa(katsottu2); katsottu2.setElokuvaId(2); katsottu2.setHenkiloId(1); 
    List<Elokuva> loytyneet; 
    loytyneet = sovellus.annaElokuvat(id2); 
    assertEquals("From: Sovellus line: 219", 0, loytyneet.size()); 
    loytyneet = sovellus.annaElokuvat(id1); 
    assertEquals("From: Sovellus line: 221", 2, loytyneet.size()); 
    assertEquals("From: Sovellus line: 222", true, loytyneet.get(0) == titanic); 
    assertEquals("From: Sovellus line: 223", true, loytyneet.get(1) == grinch); 
  } // Generated by ComTest END
}